// File auto-generated by ExposerGenerator.
using System.Reflection;
using UnityEngine;

namespace NGTools.NGRemoteScene
{
	internal sealed class ColliderExposer : ComponentExposer
	{
		public	ColliderExposer() : base(typeof(Collider))
		{
		}

		private PropertyInfo[]	cachedProperty;

		public override PropertyInfo[]	GetPropertyInfos()
		{
			if (this.cachedProperty == null)
			{
				ComponentExposer.Property.Clear();

				string	unityVersion = Application.unityVersion;

				if ((unityVersion[0] == '2' && "2018.2".CompareTo(unityVersion) <= 0) ||
					unityVersion.StartsWith("2018.1") ||
					unityVersion.StartsWith("2017.4") ||
					unityVersion.StartsWith("2017.3") ||
					unityVersion.StartsWith("2017.2") ||
					unityVersion.StartsWith("2017.1") ||
					unityVersion.StartsWith("5.6") ||
					unityVersion.StartsWith("5.5") ||
					unityVersion.StartsWith("5.4") ||
					unityVersion.StartsWith("5.3") ||
					unityVersion.StartsWith("5.2") ||
					unityVersion.StartsWith("5.1") ||
					unityVersion.StartsWith("5.0") ||
					unityVersion.StartsWith("4.7") ||
					unityVersion.StartsWith("4.6") ||
					unityVersion.StartsWith("4.5"))
				{
					ComponentExposer.Property.Add(this.type.GetProperty("enabled"));
				}

				if ((unityVersion[0] == '2' && "2018.2".CompareTo(unityVersion) <= 0) ||
					unityVersion.StartsWith("2018.1") ||
					unityVersion.StartsWith("2017.4") ||
					unityVersion.StartsWith("2017.3") ||
					unityVersion.StartsWith("2017.2") ||
					unityVersion.StartsWith("2017.1") ||
					unityVersion.StartsWith("5.6") ||
					unityVersion.StartsWith("5.5") ||
					unityVersion.StartsWith("5.4") ||
					unityVersion.StartsWith("5.3") ||
					unityVersion.StartsWith("5.2") ||
					unityVersion.StartsWith("5.1") ||
					unityVersion.StartsWith("5.0") ||
					unityVersion.StartsWith("4.7") ||
					unityVersion.StartsWith("4.6") ||
					unityVersion.StartsWith("4.5"))
				{
					ComponentExposer.Property.Add(this.type.GetProperty("isTrigger"));
				}

				if ((unityVersion[0] == '2' && "2018.2".CompareTo(unityVersion) <= 0) ||
					unityVersion.StartsWith("2018.1") ||
					unityVersion.StartsWith("2017.4") ||
					unityVersion.StartsWith("2017.3") ||
					unityVersion.StartsWith("2017.2") ||
					unityVersion.StartsWith("2017.1") ||
					unityVersion.StartsWith("5.6") ||
					unityVersion.StartsWith("5.5") ||
					unityVersion.StartsWith("5.4") ||
					unityVersion.StartsWith("5.3") ||
					unityVersion.StartsWith("5.2") ||
					unityVersion.StartsWith("5.1") ||
					unityVersion.StartsWith("5.0") ||
					unityVersion.StartsWith("4.7") ||
					unityVersion.StartsWith("4.6") ||
					unityVersion.StartsWith("4.5"))
				{
					ComponentExposer.Property.Add(this.type.GetProperty("sharedMaterial"));
				}

				if ((unityVersion[0] == '2' && "2018.2".CompareTo(unityVersion) <= 0) ||
					unityVersion.StartsWith("2018.1") ||
					unityVersion.StartsWith("2017.4") ||
					unityVersion.StartsWith("2017.3") ||
					unityVersion.StartsWith("2017.2") ||
					unityVersion.StartsWith("2017.1") ||
					unityVersion.StartsWith("5.6") ||
					unityVersion.StartsWith("5.5") ||
					unityVersion.StartsWith("5.4") ||
					unityVersion.StartsWith("5.3") ||
					unityVersion.StartsWith("5.2") ||
					unityVersion.StartsWith("5.1") ||
					unityVersion.StartsWith("5.0"))
				{
					ComponentExposer.Property.Add(this.type.GetProperty("contactOffset"));
				}

				if (ComponentExposer.Property.Count == 0)
					this.cachedProperty = ComponentExposer.EmptyArrayProperty;
				else
					this.cachedProperty = ComponentExposer.Property.ToArray();
			}

			return this.cachedProperty;
		}
	}
}