using System.Runtime.CompilerServices;
#if NGTOOLS
using NGToolsEditor;
using System.Reflection;

[assembly: AssemblyTitle(Constants.PackageTitle)]
[assembly: AssemblyDescription("Plugin made for Unity.")]
[assembly: AssemblyProduct("Unity Editor")]
[assembly: AssemblyCompany("Michaël Nguyen")]
[assembly: AssemblyCopyright("Copyright © 2016 - Infinite")]
[assembly: AssemblyFileVersion(Constants.Version)]
[assembly: AssemblyVersion("0.0.0.0")]
[assembly: InternalsVisibleTo("NGAssetFinderEditor")]
[assembly: InternalsVisibleTo("NGComponentReplacerEditor")]
[assembly: InternalsVisibleTo("NGComponentsInspectorEditor")]
[assembly: InternalsVisibleTo("NGConsoleEditor")]
[assembly: InternalsVisibleTo("NGDraggableObjectEditor")]
[assembly: InternalsVisibleTo("NGFavEditor")]
[assembly: InternalsVisibleTo("NGFullscreenBindingsEditor")]
[assembly: InternalsVisibleTo("NGHierarchyEnhancerEditor")]
[assembly: InternalsVisibleTo("NGHubEditor")]
[assembly: InternalsVisibleTo("NGInspectorGadgetEditor")]
[assembly: InternalsVisibleTo("NGMissingScriptRecoveryEditor")]
[assembly: InternalsVisibleTo("NGNavSelectionEditor")]
[assembly: InternalsVisibleTo("NGPrefsEditor")]
[assembly: InternalsVisibleTo("NGRemoteSceneEditor")]
[assembly: InternalsVisibleTo("NGRenamerEditor")]
[assembly: InternalsVisibleTo("NGScenesEditor")]
[assembly: InternalsVisibleTo("NGShaderFinderEditor")]
[assembly: InternalsVisibleTo("NGSpotlightEditor")]
[assembly: InternalsVisibleTo("NGStaticInspectorEditor")]
[assembly: InternalsVisibleTo("NGSyncFoldersEditor")]
[assembly: InternalsVisibleTo("NGHubEditor")]
[assembly: InternalsVisibleTo("RemoteModule_For_NGConsole")]
[assembly: InternalsVisibleTo("NGRemoteScene_For_NGHub")]
#endif
[assembly: InternalsVisibleTo("Assembly-CSharp")]
[assembly: InternalsVisibleTo("Assembly-CSharp-firstpass")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor")]
[assembly: InternalsVisibleTo("Assembly-CSharp-Editor-firstpass")]